
(function(){
const app=document.getElementById('app'),sound=document.getElementById('sound');
let phase='door',selected=null,muted=false,cardTimer=null;
const CARD_SRC=window.CARD_DATA||'https://assets.cdn.filesafe.space/E2BEbKIK8SvsJICq4vXY/media/6a83dd6e255b571c8ed4c2fb.png';
const packs=[{id:0,name:'MIDNIGHT',kind:'black',foil:'RED FOIL'},{id:1,name:'VOLTAGE',kind:'silver',foil:'SILVER FOIL'},{id:2,name:'VELOCITY',kind:'black',foil:'RED FOIL'},{id:3,name:'NEON',kind:'silver',foil:'SILVER FOIL'}];
/* audio */
let AC=null,master=null,metalBus=null,rapBus=null,metalTimer=null,rapTimer=null,metalStep=0,rapStep=0,intensity=0;
function ctx(){ if(!AC){ const C=window.AudioContext||window.webkitAudioContext; if(!C)return null; AC=new C(); master=AC.createGain(); master.gain.value=.56; master.connect(AC.destination); metalBus=AC.createGain(); metalBus.gain.value=0; metalBus.connect(master); rapBus=AC.createGain(); rapBus.gain.value=0; rapBus.connect(master);} if(AC.state==='suspended') AC.resume(); return AC; }
function osc(freq,dur,type,gain,bus,when){ const c=ctx(); if(!c)return; const t=when||c.currentTime,o=c.createOscillator(),g=c.createGain(); o.type=type||'sawtooth'; o.frequency.setValueAtTime(freq,t); g.gain.setValueAtTime(Math.max(.0001,gain),t); g.gain.exponentialRampToValueAtTime(.0001,t+dur); o.connect(g); g.connect(bus||master); o.start(t); o.stop(t+dur+.02); }
function noise(dur,gain,bus,when,high){ const c=ctx(); if(!c)return; const n=Math.ceil(c.sampleRate*dur),buf=c.createBuffer(1,n,c.sampleRate),a=buf.getChannelData(0); for(let i=0;i<n;i++) a[i]=Math.random()*2-1; const s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain(),t=when||c.currentTime; s.buffer=buf; f.type=high?'highpass':'lowpass'; f.frequency.value=high?5600:900; g.gain.setValueAtTime(gain,t); g.gain.exponentialRampToValueAtTime(.0001,t+dur); s.connect(f); f.connect(g); g.connect(bus||master); s.start(t); s.stop(t+dur); }
function kick(bus,when,g=.16){ const c=ctx(); if(!c)return; const o=c.createOscillator(),v=c.createGain(),t=when||c.currentTime; o.type='sine'; o.frequency.setValueAtTime(135,t); o.frequency.exponentialRampToValueAtTime(45,t+.12); v.gain.setValueAtTime(g,t); v.gain.exponentialRampToValueAtTime(.0001,t+.16); o.connect(v); v.connect(bus); o.start(t); o.stop(t+.18);} 
function snare(bus,when,g=.08){ noise(.12,g,bus,when,true); osc(190,.08,'triangle',g*.35,bus,when); }
function metalTick(){ if(!AC||muted)return; const c=AC,t=c.currentTime+.02,roots=[82.4,82.4,98,73.4,82.4,110,73.4,98],root=roots[metalStep%roots.length],lev=intensity; osc(root,.18,'sawtooth',.055+.015*lev,metalBus,t); osc(root*2,.16,'square',.018+.007*lev,metalBus,t+.008); if(lev>=1&&metalStep%2===0)kick(metalBus,t,.075+.02*lev); if(lev>=2&&metalStep%4===2)snare(metalBus,t,.035+.01*lev); if(lev>=3){ noise(.035,.018,metalBus,t,true); if(metalStep%4===0)osc(root*1.5,.13,'sawtooth',.022,metalBus,t);} metalStep++; }
function startMetal(){ const c=ctx(); if(!c||muted)return; rapBus.gain.cancelScheduledValues(c.currentTime); rapBus.gain.setTargetAtTime(0,c.currentTime,.16); metalBus.gain.cancelScheduledValues(c.currentTime); metalBus.gain.setTargetAtTime(.82,c.currentTime,.12); if(!metalTimer){ metalTick(); metalTimer=setInterval(metalTick,145); } }
function setIntensity(v){ intensity=v; startMetal(); if(master&&AC){ const level=[.42,.50,.58,.66,.72][Math.min(4,v)]||.56; master.gain.setTargetAtTime(level,AC.currentTime,.18); } }
function rapTick(){ if(!AC||muted)return; const c=AC,t=c.currentTime+.02,s=rapStep%16; if(s===0||s===6||s===10)kick(rapBus,t,s===0?.18:.13); if(s===4||s===12)snare(rapBus,t,.075); if(s%2===0)noise(.025,.018,rapBus,t,true); if(s===0||s===8)osc(55,.34,'sine',.13,rapBus,t); if(s===3||s===11)osc(49,.28,'sine',.10,rapBus,t); rapStep++; }
function startRap(){ const c=ctx(); if(!c||muted)return; metalBus.gain.cancelScheduledValues(c.currentTime); metalBus.gain.setTargetAtTime(0,c.currentTime,.22); rapBus.gain.cancelScheduledValues(c.currentTime); rapBus.gain.setTargetAtTime(.90,c.currentTime,.24); if(!rapTimer){ rapTick(); rapTimer=setInterval(rapTick,110); } }
function sfx(f,d,t,v){ osc(f,d,t||'square',v||.04,master); }
function clearTimers(){ clearTimeout(cardTimer); }
sound.addEventListener('click',()=>{ muted=!muted; sound.classList.toggle('muted',muted); if(muted){ if(master&&AC) master.gain.setTargetAtTime(0,AC.currentTime,.08);} else { ctx(); master.gain.setTargetAtTime(.56,AC.currentTime,.08); phase==='game'?startRap():startMetal(); } });
function go(p){ phase=p; render(); }
function packMarkup(p){ return `<div class="pack ${p.kind}"><div class="brand">MASON</div><div class="num">${p.id+1}</div><div class="pname">${p.name}<br>${p.foil}</div></div>`; }
function render(){ clearTimers(); if(phase==='door') door(); else if(phase==='counter') counterOpen(); else if(phase==='choose') choose(); else if(phase==='peel') peel(); else if(phase==='rip') rip(); else if(phase==='card') card(); else game(); }
function door(){ app.innerHTML=`<section class="screen door-stage"><div class="store"><div class="sign"><strong>MASON'S <b>CARD SHOP</b></strong></div><div class="frame"><div class="track"><div class="inside"><div class="counter"></div></div><div class="door" id="door" style="--dx:0px;--dp:0"><div class="glass"></div><div class="door-logo"><div class="m">M</div><small>COLLECT • RIP • REVEAL</small></div><div class="slideplate"><strong>SLIDE <i>→</i></strong><span>drag the actual door</span></div><div class="doorbar"><i></i></div></div></div></div></div><div class="vignette"></div></section>`;
 let d=document.getElementById('door'),active=false,start=0,x=0,lim=0; d.onpointerdown=e=>{ ctx(); setIntensity(0); active=true; start=e.clientX-x; if(d.setPointerCapture) d.setPointerCapture(e.pointerId); }; d.onpointermove=e=>{ if(!active)return; lim=Math.max(135,d.clientWidth*.63); x=Math.max(0,Math.min(lim,e.clientX-start)); d.style.setProperty('--dx',x+'px'); d.style.setProperty('--dp',x/lim); }; d.onpointerup=d.onpointercancel=()=>{ if(!active)return; active=false; if(x>(lim||d.clientWidth*.63)*.52){ sfx(115,.1,'sawtooth',.06); d.style.transition='transform .42s cubic-bezier(.2,.9,.2,1)'; d.style.setProperty('--dx',d.clientWidth*1.08+'px'); setTimeout(()=>go('counter'),450);} else { d.style.transition='transform .3s ease'; x=0; d.style.setProperty('--dx','0px'); d.style.setProperty('--dp',0); setTimeout(()=>d.style.transition='',330);} }
 }
function counterOpen(){ setIntensity(1); app.innerHTML=`<section class="screen counter-stage"><header><div class="eyebrow">THE COUNTER</div><h1 class="impact">OPEN THE BOX</h1><p>Drag down to slide the lid back, then choose your pack</p></header><div class="counter-wrap"><div class="spark s1"></div><div class="spark s2"></div><div class="spark s3"></div><div class="spark s4"></div><div class="hero-box" id="heroBox"><div class="hero-base"></div><div class="hero-lid" id="heroLid" style="--lid:0deg"><strong>MASON</strong></div></div><div class="lid-cue">Drag down <i>↓</i></div></div><div class="vignette"></div></section>`;
 let box=document.getElementById('heroBox'),lid=document.getElementById('heroLid'),active=false,startY=0,open=0; function apply(){ lid.style.setProperty('--lid',(-open*18)+'deg'); lid.style.transform=`translateY(${-105*open}px) rotateX(${-18*open}deg)`; }
 box.onpointerdown=e=>{ ctx(); active=true; startY=e.clientY-open*130; if(box.setPointerCapture) box.setPointerCapture(e.pointerId); };
 box.onpointermove=e=>{ if(!active)return; open=Math.max(0,Math.min(1,(e.clientY-startY)/130)); apply(); };
 box.onpointerup=box.onpointercancel=()=>{ if(!active)return; active=false; if(open>.55){ open=1; apply(); setIntensity(2); sfx(160,.11,'sawtooth',.06); setTimeout(()=>go('choose'),350);} else { const from=open,t0=performance.now(); function step(t){ const u=Math.min(1,(t-t0)/220); open=from*(1-u); apply(); if(u<1) requestAnimationFrame(step);} requestAnimationFrame(step);} };
 }
function choose(){ setIntensity(2); app.innerHTML=`<section class="screen choose"><header><div class="eyebrow">PACK SELECTION</div><h1 class="impact">CHOOSE A PACK</h1><p>Four packs. One pull. Your choice stays yours.</p></header><div class="boxscene"><div class="cardbox"><div class="lid"></div><div class="base"></div><div class="packs">${packs.map(p=>`<button class="slot" data-id="${p.id}">${packMarkup(p)}</button>`).join('')}</div></div><div class="foot">Tap the pack you want • it comes out of the box</div></div><div class="vignette"></div></section>`;
 let lock=false; [...document.querySelectorAll('.slot')].forEach(s=>s.onpointerup=()=>{ if(lock)return; lock=true; selected=packs[+s.dataset.id]; sfx(165,.09,'sawtooth',.07); [...document.querySelectorAll('.slot')].forEach(q=>{ if(q!==s) q.classList.add('faded'); }); s.classList.add('chosen'); setTimeout(()=>go('peel'),980); }); }
function peel(){ if(!selected) selected=packs[0]; setIntensity(2); app.innerHTML=`<section class="screen peel"><div class="peelcopy"><div class="eyebrow">PACK ${selected.id+1} • ${selected.name}</div><h1 class="impact">PEEL THE FOIL</h1><p>Put your finger on the pack and drag downward</p></div><div class="peelzone" id="pz"><div class="wrapbody ${selected.kind}"><div class="inner"></div><div class="tear"></div><div class="plabel"><strong>${selected.id+1}</strong><span>${selected.name} • ${selected.foil}</span></div><div class="pmeter"><i></i></div></div><div class="foil"></div><div class="finger">☝️</div></div><div class="vignette"></div></section>`;
 let z=document.getElementById('pz'),active=false,startY=0,p=0,done=false; const apply=()=>z.style.setProperty('--peel',p.toFixed(3)); z.onpointerdown=e=>{ ctx(); active=true; startY=e.clientY-p*150; if(z.setPointerCapture) z.setPointerCapture(e.pointerId); const f=document.querySelector('.finger'); if(f) f.remove();}; z.onpointermove=e=>{ if(!active||done)return; p=Math.max(0,Math.min(1,(e.clientY-startY)/150)); apply();}; z.onpointerup=z.onpointercancel=()=>{ if(!active||done)return; active=false; if(p>.68){ done=true; p=1; apply(); setIntensity(3); sfx(860,.12,'sawtooth',.06); setTimeout(()=>go('rip'),420);} else { const from=p,t0=performance.now(); function a(t){ const u=Math.min(1,(t-t0)/240); p=from*(1-u); apply(); if(u<1) requestAnimationFrame(a); } requestAnimationFrame(a);} };
 }
function rip(){ setIntensity(3); app.innerHTML=`<section class="screen rip"><div class="ripcopy"><div class="eyebrow">FINAL REVEAL</div><h1 class="impact">RIP IT OPEN</h1><p>Drag downward to rip it open</p></div><div class="ripstage" id="ripstage"><div class="rippack ${selected.kind}"></div><div class="splitL"></div><div class="splitR"></div><div class="ripline"></div><div class="ripcard"><img src="${CARD_SRC}" alt="Mason's card" loading="eager" decoding="async" fetchpriority="high" referrerpolicy="no-referrer"></div></div><div class="vignette"></div></section>`;
 const rs=document.getElementById('ripstage'); let active=false,startY=0,p=0,done=false; const apply=()=>rs.style.setProperty('--rip',p.toFixed(3)); rs.onpointerdown=e=>{ ctx(); active=true; startY=e.clientY-p*140; if(rs.setPointerCapture) rs.setPointerCapture(e.pointerId);}; rs.onpointermove=e=>{ if(!active||done)return; p=Math.max(0,Math.min(1,(e.clientY-startY)/140)); apply();}; rs.onpointerup=rs.onpointercancel=()=>{ if(!active||done)return; active=false; if(p>.6){ done=true; p=1; apply(); setIntensity(4); sfx(92,.18,'sawtooth',.07); setTimeout(()=>go('card'),520);} else { const from=p,t0=performance.now(); function a(t){ const u=Math.min(1,(t-t0)/220); p=from*(1-u); apply(); if(u<1) requestAnimationFrame(a);} requestAnimationFrame(a);} };
 }
function card(){ setIntensity(4); app.innerHTML=`<section class="screen cardstage"><div class="cardwrap"><div class="eyebrow">PACK ${((selected?selected.id:0)+1)} • THE PULL</div><div class="cardframe"><img src="${CARD_SRC}" alt="Michigan Sports Card Shows Best Card Show Ever card" loading="eager" decoding="async" fetchpriority="high" referrerpolicy="no-referrer"><div class="shine"></div></div><h1>MASON <span>CARPENTER</span></h1><p>Best Card Show • Collector Pull</p><div class="next">Next: Infinite Hoops</div></div><div class="vignette"></div></section>`; sfx(58,.25,'sawtooth',.08); cardTimer=setTimeout(()=>go('game'),5000); document.querySelector('.cardstage').onpointerup=()=>go('game'); }
function game(){
 startRap();
 app.innerHTML=`<section class="screen game domgame"><div class="arena-lights"></div><div class="court2"></div><div class="ghead"><div><h1>INFINITE <span>HOOPS</span></h1><p>Pull back and release • play forever</p></div><div class="score"><small>SCORE / STREAK</small><b><span id="sc">0</span> · <span id="st">0</span></b></div></div><div class="backboard2"></div><div class="rim2"></div><div class="net2"></div><div class="shotzone2" id="shotzone2"><div class="aim2" id="aim2"></div><div class="ball2" id="ball2"></div></div><div class="swish2" id="swish2">SWISH!</div><div class="hint2">Pull back and release</div></section>`;
 domHoops();
}
function domHoops(){
 const z=document.getElementById('shotzone2'),el=document.getElementById('ball2'),aim=document.getElementById('aim2');
 if(!z||!el)return;
 let W=innerWidth,H=innerHeight,score=0,streak=0,drag=false,shot=false,made=false,last=performance.now(),resetPending=false;
 const b={x:W*.5,y:H*.80,vx:0,vy:0,r:23,spin:0};
 const hx=()=>W*.5, hy=()=>H*.358, rimHalf=()=>Math.min(54,W*.135);
 function ui(){ const a=document.getElementById('sc'),c=document.getElementById('st'); if(a)a.textContent=score;if(c)c.textContent=streak; }
 function draw(){ el.style.left=b.x+'px';el.style.top=b.y+'px';el.style.transform='rotate('+b.spin+'rad)'; }
 function reset(miss){ if(miss)streak=0; W=innerWidth;H=innerHeight;b.x=W*.5;b.y=H*.80;b.vx=b.vy=b.spin=0;drag=shot=made=resetPending=false;if(aim)aim.style.display='none';ui();draw(); }
 function pt(e){ const r=z.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}; }
 function showAim(){ if(!drag||!aim)return; const dx=hx()-b.x,dy=hy()-b.y;aim.style.display='block';aim.style.left=b.x+'px';aim.style.top=b.y+'px';aim.style.width=Math.min(215,Math.hypot(dx,dy)*.55)+'px';aim.style.transform='rotate('+Math.atan2(dy,dx)+'rad)'; }
 z.onpointerdown=e=>{ ctx();const q=pt(e);if(shot||Math.hypot(q.x-b.x,q.y-b.y)>62)return;drag=true;try{z.setPointerCapture(e.pointerId)}catch(_){}showAim(); };
 z.onpointermove=e=>{ if(!drag||shot)return;const q=pt(e);b.x=Math.max(30,Math.min(W-30,q.x));b.y=Math.max(H*.72,Math.min(H*.92,q.y));draw();showAim(); };
 z.onpointerup=e=>{ if(!drag||shot)return;drag=false;if(aim)aim.style.display='none';const t=.78,g=900;b.vx=(hx()-b.x)/t;b.vy=(hy()-b.y-.5*g*t*t)/t;shot=true;made=false;sfx(105,.05,'sine',.04); };
 z.onpointercancel=()=>{ if(drag)reset(false); };
 function collide(rx,ry){ const dx=b.x-rx,dy=b.y-ry,d=Math.hypot(dx,dy),m=b.r+6;if(d<m&&d>0){const nx=dx/d,ny=dy/d;b.x=rx+nx*m;b.y=ry+ny*m;const dot=b.vx*nx+b.vy*ny;if(dot<0){b.vx-=1.52*dot*nx;b.vy-=1.52*dot*ny;b.vx*=.84;b.vy*=.84;}} }
 function finish(miss){ if(resetPending)return;resetPending=true;setTimeout(()=>{ if(phase==='game')reset(miss); },150); }
 function tick(now){ if(phase!=='game'||!document.body.contains(z))return;const dt=Math.min(.03,(now-last)/1000||.016);last=now;if(shot){const py=b.y;b.vy+=900*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;b.spin+=b.vx*dt*.011;collide(hx()-rimHalf(),hy());collide(hx()+rimHalf(),hy());if(!made&&py<hy()&&b.y>=hy()&&b.vy>0&&Math.abs(b.x-hx())<rimHalf()*.72){made=true;score++;streak++;ui();sfx(730,.08,'sine',.05);const sw=document.getElementById('swish2');if(sw){sw.classList.remove('go');void sw.offsetWidth;sw.classList.add('go');}}if(b.x<-90||b.x>W+90||b.y>H+100||b.y<-170)finish(!made);draw();}requestAnimationFrame(tick); }
 addEventListener('resize',()=>{if(phase==='game')reset(false)},{passive:true});reset(false);requestAnimationFrame(tick);
}
 render();
})();
